#pragma once

#include "CoreMinimal.h"

class AZoneGraphData;
class UFlexNetworkSubsystem;
class UWorld;

struct FLEXNETWORKZONEGRAPH_API FFlexZoneGraphGenerationOptions
{
	/** Distance between authored ZoneShape points along FlexNetwork Bezier curves. */
	float SampleSpacing = 200.f;

	/** Adds the profile's explicit and generated roadside sidewalks as pedestrian lanes. */
	bool bIncludePedestrianLanes = true;

	/** Removes actors from the previous FlexNetwork ZoneGraph export before generating. */
	bool bReplaceExisting = true;

	/** Registers the shared tag palette and applies it to MassTraffic/MassCrowd settings. */
	bool bConfigureMassAI = true;
};

struct FLEXNETWORKZONEGRAPH_API FFlexZoneGraphGenerationResult
{
	int32 SegmentShapes = 0;
	int32 IntersectionShapes = 0;
	int32 CrosswalkShapes = 0;
	int32 PedestrianCornerShapes = 0;
	int32 RemovedActors = 0;
	AZoneGraphData* DataActor = nullptr;

	int32 GetShapeCount() const { return SegmentShapes + IntersectionShapes + CrosswalkShapes + PedestrianCornerShapes; }
};

/** Full graph exporter adapted from ProceduralRoads' MapModel-to-ZoneGraph pipeline. */
class FLEXNETWORKZONEGRAPH_API FFlexNetworkZoneGraphGenerator
{
public:
	static FFlexZoneGraphGenerationResult Generate(
		const UFlexNetworkSubsystem& Network,
		UWorld& World,
		const FFlexZoneGraphGenerationOptions& Options = FFlexZoneGraphGenerationOptions());

	/** Removes only AZoneShape/AZoneGraphData actors tagged as generated by this exporter. */
	static int32 RemoveGeneratedActors(UWorld& World);
};
